### ISSUE TITLE
发票验证 receiptData 

### ISSUE THREAD

**Issue by zhouhesheng** [zhongzichang/spring-iap#3]
一直显示 21002， The data in the receipt-data property was malformed

post的receiptData 不是base64的字符串么？为什么是 byte[]

**Comment by zhongzichang** [comment]
数据是byte[]，只是byte[]不能直接封装到 json 里面，需要序列化成 base64 字符串。如果用你 spring 的话试试就知道，byte[] 和 base64 字符串的相互转换是自动完成，在写代码的时候直接用 byte[] 就可以了。
